services:
  - type: web
    name: petcare-hub
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py loaddata /opt/render/project/src/fixtures/areas.json --verbosity 2"
    startCommand: "gunicorn petcare.wsgi"