# Generated by Django 5.2.7 on 2026-09-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0047_load_area_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=50),
        ),
    ]
