# Generated by Django 5.2.7 on 2026-09-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0048_alter_area_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
