# Generated by Django 5.2.7 on 2026-09-26 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0049_alter_feedback_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vet',
            name='contact',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Contact number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
