# Generated by Django 5.2.7 on 2026-09-30 13:18

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0051_alter_customer_email_alter_customer_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_report',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces.', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='deliveryboy_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image_path',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_img_path',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters and spaces.', regex='^[a-zA-Z\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='vet',
            name='vet_profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
