# Generated by Django 5.2.7 on 2026-10-01 15:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0052_alter_appointment_medical_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='documents',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
