# Generated by Django 5.2.7 on 2026-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0053_alter_vet_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
